# Generated by Django 2.2.28 on 2023-06-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhyu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sweer23',
            name='mjui888',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sweer23',
            name='smnv6',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
