# Generated by Django 2.2.28 on 2023-06-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhyu', '0002_auto_20230601_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='sweer23',
            name='bvr34',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
